const path = require('path');
const logger = require('../utils/logger');

/**
 * Generates the access URL for an uploaded file
 * @param {string} filename - Filename generated by multer
 * @returns {string|null} Relative path or access url
 */
const getMediaUrl = (filename) => {
  if (!filename) return null;
  
  // Expose file statically under the '/Storage' route
  const relativeUrl = `/Storage/${filename}`;
  logger.info(`Generated local storage access URL: ${relativeUrl}`);
  return relativeUrl;
};

module.exports = {
  getMediaUrl
};
